#!/bin/bash

if [[ -z "$1" ]] ; then
	echo "defaulting to NFS boot"
	set -- nfs
fi

if [[ ! -d "${1}root" ]] ; then
	echo "No directory ${1}root"
	exit 1
fi

extra_args=()

if [[ "$1" == 'rd' ]] ; then
	extra_args+=(write 0x43300000 rootfs.cpio.uboot)
fi

sunxi-fel version || exit 1

sunxi-fel -v uboot u-boot-sunxi-with-spl.bin \
	write 0x42000000 zImage \
	write 0x43000000 board.dtb \
	write 0x43100000 ${1}root/felboot.scr \
	"${extra_args[@]}"
